# Generated by Django 4.2.28 on 2026-02-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriAlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori Alat',
            },
        ),
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(max_length=150)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('kondisi', models.CharField(choices=[('baik', 'Baik'), ('rusak', 'Rusak'), ('hilang', 'Hilang')], default='baik', max_length=20)),
                ('denda_per_hari', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_alat', to='inventory.kategorialat')),
            ],
            options={
                'verbose_name_plural': 'Alat',
            },
        ),
    ]
