# Generated by Django 4.2.28 on 2026-02-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='lokasi',
            field=models.CharField(default='Sarpras', max_length=100, verbose_name='Lokasi Penyimpanan'),
            preserve_default=False,
        ),
    ]
