# Generated by Django 4.2.28 on 2026-02-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alat_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='denda_ganti_rugi',
            field=models.PositiveIntegerField(default=0, help_text='Nominal harga ganti rugi jika barang hilang/rusak'),
        ),
    ]
