# Generated by Django 4.2.28 on 2026-02-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alat_denda_ganti_rugi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alat',
            name='nama_alat',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
