# Generated by Django 6.0.3 on 2026-04-07 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_alat_nama_alat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alat',
            name='stok',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
