# Generated by Django 4.2.28 on 2026-02-10 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alat_denda_ganti_rugi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('waktu_pinjam', models.DateTimeField(default=django.utils.timezone.now)),
                ('waktu_kembali_rencana', models.DateTimeField()),
                ('denda_per_hari', models.PositiveIntegerField(default=5000, help_text='Nominal denda per hari')),
                ('status', models.CharField(choices=[('dipinjam', 'Sedang Dipinjam'), ('dikembalikan', 'Sudah Dikembalikan'), ('hilang', 'Hilang')], default='dipinjam', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('alat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_alat', to='inventory.alat')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peminjaman_petugas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peminjaman',
                'verbose_name_plural': 'Data Peminjaman',
                'ordering': ['-waktu_pinjam'],
            },
        ),
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_kembali_realisasi', models.DateTimeField(auto_now_add=True)),
                ('kondisi_akhir', models.CharField(choices=[('baik', 'Baik'), ('rusak', 'Rusak'), ('hilang', 'Hilang')], default='baik', max_length=20)),
                ('terlambat', models.IntegerField(default=0)),
                ('total_denda', models.IntegerField(default=0)),
                ('peminjaman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pengembalian', to='borrowings.peminjaman')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengembalian_petugas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengembalian',
                'verbose_name_plural': 'Data Pengembalian',
            },
        ),
    ]
