# Generated by Django 4.2.28 on 2026-02-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='denda_per_hari',
            field=models.PositiveIntegerField(default=0, help_text='Nominal denda per hari (snapshot)'),
        ),
    ]
