# Generated by Django 4.2.28 on 2026-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0002_alter_peminjaman_denda_per_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengembalian',
            name='biaya_kerusakan',
            field=models.PositiveIntegerField(default=0, help_text='Biaya perbaikan jika barang rusak (diinput petugas)'),
        ),
    ]
