# Generated by Django 4.2.28 on 2026-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0003_pengembalian_biaya_kerusakan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengembalian',
            name='catatan',
            field=models.TextField(blank=True, help_text='Detail kerusakan atau keterangan tambahan', null=True),
        ),
    ]
