# Generated by Django 4.2.28 on 2026-02-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0004_pengembalian_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('dipinjam', 'Sedang Dipinjam'), ('dikembalikan', 'Sudah Dikembalikan'), ('hilang', 'Hilang')], default='dipinjam', max_length=20),
        ),
    ]
