# Generated by Django 4.2.28 on 2026-02-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0005_alter_peminjaman_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('dipinjam', 'Sedang Dipinjam'), ('dikembalikan', 'Sudah Dikembalikan'), ('hilang', 'Hilang'), ('ditolak', 'Ditolak')], default='dipinjam', max_length=20),
        ),
    ]
