# Generated by Django 4.2.28 on 2026-02-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0006_alter_peminjaman_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengembalian',
            name='status_pembayaran',
            field=models.CharField(choices=[('lunas', 'Lunas'), ('belum_lunas', 'Belum Lunas')], default='belum_lunas', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengembalian',
            name='biaya_kerusakan',
            field=models.PositiveIntegerField(help_text='Biaya perbaikan jika barang rusak (diinput petugas)'),
        ),
    ]
