# Generated by Django 4.2.28 on 2026-02-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0007_pengembalian_status_pembayaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengembalian',
            name='biaya_kerusakan',
            field=models.PositiveIntegerField(default=0, help_text='Biaya perbaikan jika barang rusak (diinput petugas)'),
        ),
    ]
